name: Build & Publish to itch.io

on:
  workflow_dispatch:

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  PROJECT_PATH: .

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository ðŸ”Ž
        uses: actions/checkout@v2
        with:
          lfs: true
  
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library
          
      # Build
      - name: Build project ðŸ› 
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          unityVersion: 2020.2.3f1
          targetPlatform: StandaloneWindows64
          customParameters: "-nographics"
          buildName: win
          buildsPath: Out
          allowDirtyBuild: true

      # Upload build
      - name: Upload build ðŸ’Ž
        uses: actions/upload-artifact@v2
        with:
          name: win
          path: Out
          
      # Publish
      - name: Publish with butler ðŸ•¹
        uses: josephbmanley/butler-publish-itchio-action@v1.0.2
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ci-test-project
          ITCH_USER: pyrbin
          PACKAGE: Out
